#!/bin/bash

if (( $# != 6 )); then 
    echo "Usage: riemann <delta x> <lower limit> <upper limit> <a> <b> <c>"
    exit 1
fi

DELTA=$1
LOWER=$2
UPPER=$3
A=$4
B=$5
C=$6
TOTAL=0

while ((${LOWER} < ${UPPER})); do
    ((TOTAL=TOTAL+(A*LOWER*LOWER+B*LOWER+C)*DELTA))
    ((LOWER=LOWER+DELTA))
done

echo ${TOTAL}
exit 0