#! /bin/bash

echo "--------PART 1  TESTS--------"
{ part1=$(./test-part1 | tee /dev/fd/3 | tail -n 1); } 3>&1
echo "--------PART 2  TESTS--------"
{ part2=$(./test-part2 | tee /dev/fd/3 | tail -n 1); } 3>&1

part1arr=(${part1//,/ })
part2arr=(${part2//,/ })

SCORE=$((part1arr[0] + part2arr[0]))
TOTAL=$((part1arr[1] + part2arr[1]))

echo Score,Total
echo ${SCORE},${TOTAL}
